### PR TITLE
Update list of media fields

### PR DESCRIPTION
**Pull request by elizoller**
add a config field for media_fields and use it in the getFileUuid method in the utils

for #35

### CODE REVIEW

**Comment by mjordan** [comment]
New config option is not showing up without either uninstalling/reinstalling the module or loading the config manually. In both cases other options are reset to defaults. Do you know of a way to load just the new config option, so admins don't need to reinstall?

**Comment by elizoller** [comment]
The default value isn't showing up or the field isn't showing up?

**Comment by mjordan** [comment]
Default value.

**Comment by mjordan** [comment]
I tested by installing the module on a clean vagrant, in its master branch. Then viewed the form. Then changed to your branch. The new field showed up empty. Once I reinstalled, the new default value showed up. Clearing cache didn't help.

I thought setting the default value would be non-backward-breaking, but it looks like it won't be unless we do something to load it.

**Comment by elizoller** [comment]
2 options i can think of:
1. we add something like 
```
'#default_value' => ($config->get('media_fields') ? $config->get('media_fields') : "field_media_file\nfield_media_document\nfield_media_image\nfield_media_video_file\nfield_media_audio_file"),
``` 
here: https://github.com/mjordan/islandora_riprap/pull/37/files#diff-9860362eac3624685d0b3759c4fd89ebR130
or 
2. tell people to use a drush command to set a single config value like
`drush config:set islandora_riprap.settings media_fields "field_media_file\nfield_media_document\nfield_media_image\nfield_media_video_file\nfield_media_audio_file"`

**Comment by mjordan** [comment]
I like the first one. Can you add it or would you rather I merge and add it in a separate PR? Am happy to test it on my local copy first.

**Comment by elizoller** [comment]
i can add it

**Comment by mjordan** [comment]
Giving it a quick test right now.

**Comment by mjordan** [comment]
Yup! Also need to add it at https://github.com/mjordan/islandora_riprap/pull/37/files#diff-f8bd72871f94b4c580f658c3071a8f97R32 I think.

**Comment by mjordan** [comment]
Super, thanks!

**Pull request merged**
